force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <label>Vote</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting__c/Voting__c.object-meta.xml
<CustomObject>
    <label>Voting</label>
    <nameField>
        <label>Voting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting__c/fields/Voting_Type__c.field-meta.xml
<CustomField>
    <fullName>Voting_Type__c</fullName>
    <label>Voting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Idea</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ManageVotings.cls
public with sharing class ManageVotings {
    public ManageVotings() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Voting__c> getList(String recordId) {
        Id ids = Id.valueOf(recordId);
        return [select Id, Name, Voting_Type__c from Voting__c where Voting_Campaign__r.Id = :ids];
    }

    
    @AuraEnabled(cacheable=true)
    public static List<Voting__c> getVotingsWithoutAns(String recordId) {
        Id ids = Id.valueOf(recordId);
        return [select Id, Name from Voting__c where Id not in (select Voting__c from Vote__c) and Voting_Campaign__r.Id = :ids];
    }
}