force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <label>Vote</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Question_Option__c.field-meta.xml
<CustomField>
    <fullName>Voting_Question_Option__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Question Option</label>
    <referenceTo>Voting_Question_Option__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting__c/Voting__c.object-meta.xml
<CustomObject>
    <label>Voting</label>
    <nameField>
        <label>Voting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Campaign__c/fields/VotingLocation__c.field-meta.xml
<CustomField>
    <fullName>VotingLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>VotingLocation</label>
    <referenceTo>Voting_Location__c</referenceTo>
    <relationshipLabel>Voting Campaigns</relationshipLabel>
    <relationshipName>Voting_Campaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Location__c/Voting_Location__c.object-meta.xml
<CustomObject>
    <label>Voting Location</label>
    <nameField>
        <label>Voting Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting_Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Question_Option__c/Voting_Question_Option__c.object-meta.xml
<CustomObject>
    <label>Voting Question Option</label>
    <nameField>
        <label>Voting Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Question Options</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Question_Option__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Voting Question Options</relationshipLabel>
    <relationshipName>Voting_Question_Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChartData.cls
public with sharing class ChartData {
    public ChartData() {

    }
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getVotes(String votingId){
        Id ids = Id.valueOf(votingId);
        return [select count(Id), Voting_Question_Option__r.Name from Vote__c 
                              where Voting__c = :ids group by Voting_Question_Option__r.Name];
    }
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getVotesperVoting(String campaignId){
        Id ids = Id.valueOf(campaignId);
        return [select count(Id), Voting__r.Name from Vote__c where Voting_Campaign__c = :ids group by Voting__r.Name];
    }

    //chart of locations
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> locationsPerVotingCampaigns(){
        return [select count(Id), VotingLocation__r.Name from Voting_Campaign__c group by VotingLocation__r.Name];
    }


}