force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <label>Vote</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Question_Option__c.field-meta.xml
<CustomField>
    <fullName>Voting_Question_Option__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Question Option</label>
    <referenceTo>Voting_Question_Option__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting__c/Voting__c.object-meta.xml
<CustomObject>
    <label>Voting</label>
    <nameField>
        <label>Voting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Question_Option__c/Voting_Question_Option__c.object-meta.xml
<CustomObject>
    <label>Voting Question Option</label>
    <nameField>
        <label>Voting Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Question Options</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Question_Option__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Voting Question Options</relationshipLabel>
    <relationshipName>Voting_Question_Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ManageVotes.cls
public with sharing class ManageVotes {
    public ManageVotes() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Voting_Question_Option__c> getVotingOptions(String votingId){
        Id ids = Id.valueOf(votingId);
        return [select Name from Voting_Question_Option__c where Voting__c = :ids];
    }

    @AuraEnabled(cacheable=true)
    public static List<Vote__c> getVotesFromCampaign(String campaignId){
        Id ids = Id.valueOf(campaignId);
        Id userId = userInfo.getUserId();
        return [select Voting__r.Name, Voting_Campaign__r.Name, Voting_Question_Option__r.Name from Vote__c where Voting_Campaign__c = :ids and OwnerId = :userId];
    }
}