force-app/main/default/objects/Voting__c/Voting__c.object-meta.xml
<CustomObject>
    <label>Voting</label>
    <nameField>
        <label>Voting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Campaign__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Age_Range_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0-18</fullName>
        <default>true</default>
        <label>0-18</label>
    </customValue>
    <customValue>
        <fullName>19-25</fullName>
    </customValue>
    <customValue>
        <fullName>26-35</fullName>
    </customValue>
    <customValue>
        <fullName>36-45</fullName>
    </customValue>
    <customValue>
        <fullName>46-55</fullName>
    </customValue>
    <customValue>
        <fullName>55+</fullName>
    </customValue>
    <masterLabel>Age Range Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ManageVotingCampaigns.cls
public with sharing class ManageVotingCampaigns {
    public ManageVotingCampaigns() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Voting_Campaign__c> getVotingCamp(){
        return [select Id, Name, Start_Date__c, End_Date__c, Status__c, Age_Range__c from Voting_Campaign__c];
    }

    
    @AuraEnabled(cacheable=true)
    public static List<Voting_Campaign__c> getActiveVotingCamp(){
        return [select Id, Name, Start_Date__c, End_Date__c, Status__c from Voting_Campaign__c where Status__c = 'In progress' and Id in (select Voting_Campaign__c from Voting__c)];
    }

    @AuraEnabled(cacheable=true)
    public static List<Voting_Campaign__c> getEndingCampaigns(){
        Date todaysDate = System.today();
        return [select Id, Name, End_Date__c, Status__c from Voting_Campaign__c where (Status__c != 'Stopped' and End_Date__c = :todaysDate)];
    }

}