force-app/main/default/objects/User/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Campaign__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Age_Range_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0-18</fullName>
        <default>true</default>
        <label>0-18</label>
    </customValue>
    <customValue>
        <fullName>19-25</fullName>
    </customValue>
    <customValue>
        <fullName>26-35</fullName>
    </customValue>
    <customValue>
        <fullName>36-45</fullName>
    </customValue>
    <customValue>
        <fullName>46-55</fullName>
    </customValue>
    <customValue>
        <fullName>55+</fullName>
    </customValue>
    <masterLabel>Age Range Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ManageUsers.cls
public with sharing class ManageUsers {
    
    @AuraEnabled(cacheable=true)
    public static List<User> getGroupMembers(String campaignId, String groupName)
    {
        Id formattedCampaignId = Id.valueOf(campaignId);
        String formattedGroupName;
        String ageRange;
        for(Voting_Campaign__c camp : [select Age_Range__c from Voting_Campaign__c where Voting_Campaign__c.Id = :formattedCampaignId])
        {
            ageRange = camp.Age_Range__c;
        }

        if(groupName == 'Voter') {
            String formattedAge = ageRange.remove('+').replace('-', '_');
            formattedGroupName = (groupName+'_'+formattedAge);
        }
        else if(groupName == 'Moderator' || groupName == 'Analyst') {
            if(Integer.valueOf(ageRange.substring(0,1)) < 2) {
                formattedGroupName = (groupName+'_under_25');
            }
            else formattedGroupName = (groupName+'_above_25');
        }
        List<User> allGroupMembers = [select Username from User where isActive = TRUE and Id in 
            (select UserOrGroupId from GroupMember where Group.DeveloperName = :formattedGroupName)];
        return allGroupMembers;
    }
}