force-app/main/default/objects/User/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Campaign__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/fields/VotingLocation__c.field-meta.xml
<CustomField>
    <fullName>VotingLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>VotingLocation</label>
    <referenceTo>Voting_Location__c</referenceTo>
    <relationshipLabel>Voting Campaigns</relationshipLabel>
    <relationshipName>Voting_Campaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Location__c/Voting_Location__c.object-meta.xml
<CustomObject>
    <label>Voting Location</label>
    <nameField>
        <label>Voting Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting_Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Age_Range_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0-18</fullName>
        <default>true</default>
        <label>0-18</label>
    </customValue>
    <customValue>
        <fullName>19-25</fullName>
    </customValue>
    <customValue>
        <fullName>26-35</fullName>
    </customValue>
    <customValue>
        <fullName>36-45</fullName>
    </customValue>
    <customValue>
        <fullName>46-55</fullName>
    </customValue>
    <customValue>
        <fullName>55+</fullName>
    </customValue>
    <masterLabel>Age Range Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Tests/TestManageUsers.cls
@isTest
public with sharing class TestManageUsers {
    @testSetup
    static void setup() {
        Voting_Location__c newLocation = new Voting_Location__c(Name='Testowe', Country__c='Poland', City__c='Lublin');
        Database.insert(newLocation);
        Voting_Campaign__c newCampaign = new Voting_Campaign__c(Name='TestManageUsers',Start_Date__c=System.today(), End_Date__c=System.today()+2, Age_Range__c='46-55', VotingLocation__c=newLocation.Id);
        Database.insert(newCampaign);
    }

    @isTest
    static void testGetGroupMembersSuccess() {
        Voting_Campaign__c newCampaign = [select Id from Voting_Campaign__c where Name = 'TestManageUsers' limit 1];
        Profile voter = [SELECT Id FROM Profile WHERE Name='Voter']; 
        List<User> users = [select Username from User where ProfileId = :voter.Id];
        
        List<User> resultVoter = ManageUsers.getGroupMembers(newCampaign.Id, 'Voter');
        System.assertNotEquals(null, resultVoter, 'No voter was found in the allocated group');
        
        List<User> resultMod = ManageUsers.getGroupMembers(newCampaign.Id, 'Moderator');
        System.assertNotEquals(null, resultMod, 'No moderator was found in the allocated group');

        List<User> resultAna = ManageUsers.getGroupMembers(newCampaign.Id, 'Analyst');
        System.assertNotEquals(null, resultAna, 'No moderator was found in the allocated group');

    }
    @isTest
    static void testGetGroupMembersFailure() {
        Voting_Campaign__c newCampaign = [select Id from Voting_Campaign__c where Name = 'TestManageUsers' limit 1];
        List<User> result = ManageUsers.getGroupMembers(newCampaign.Id, 'Standard User');
        System.assertEquals(null, result, 'No voter was found in the allocated group');
        
    }

}