force-app/main/default/objects/User/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vote__c/Vote__c.object-meta.xml
<CustomObject>
    <label>Vote</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vote__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vote__c/fields/Voting_Question_Option__c.field-meta.xml
<CustomField>
    <fullName>Voting_Question_Option__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Question Option</label>
    <referenceTo>Voting_Question_Option__c</referenceTo>
    <relationshipLabel>Votes</relationshipLabel>
    <relationshipName>Votes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting__c/Voting__c.object-meta.xml
<CustomObject>
    <label>Voting</label>
    <nameField>
        <label>Voting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting__c/fields/Voting_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Voting_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting Campaign</label>
    <referenceTo>Voting_Campaign__c</referenceTo>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Campaign__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <defaultValue>&quot;0-18&quot;</defaultValue>
    <label>Age Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Range_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voting_Campaign__c/fields/VotingLocation__c.field-meta.xml
<CustomField>
    <fullName>VotingLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>VotingLocation</label>
    <referenceTo>Voting_Location__c</referenceTo>
    <relationshipLabel>Voting Campaigns</relationshipLabel>
    <relationshipName>Voting_Campaigns</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voting_Location__c/Voting_Location__c.object-meta.xml
<CustomObject>
    <label>Voting Location</label>
    <nameField>
        <label>Voting Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting_Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Question_Option__c/Voting_Question_Option__c.object-meta.xml
<CustomObject>
    <label>Voting Question Option</label>
    <nameField>
        <label>Voting Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Question Options</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Question_Option__c/fields/Voting__c.field-meta.xml
<CustomField>
    <fullName>Voting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Voting</label>
    <referenceTo>Voting__c</referenceTo>
    <relationshipLabel>Voting Question Options</relationshipLabel>
    <relationshipName>Voting_Question_Options</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Age_Range_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0-18</fullName>
        <default>true</default>
        <label>0-18</label>
    </customValue>
    <customValue>
        <fullName>19-25</fullName>
    </customValue>
    <customValue>
        <fullName>26-35</fullName>
    </customValue>
    <customValue>
        <fullName>36-45</fullName>
    </customValue>
    <customValue>
        <fullName>46-55</fullName>
    </customValue>
    <customValue>
        <fullName>55+</fullName>
    </customValue>
    <masterLabel>Age Range Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Tests/TestManageVotings.cls
@isTest
public with sharing class TestManageVotings {
    @testSetup
    static void setup() {
      Voting_Location__c newLocation = new Voting_Location__c(Name='Testowe', Country__c='Poland', City__c='Lublin');
        Database.insert(newLocation);
        
        Voting_Campaign__c newCampaign = 
            new Voting_Campaign__c(Name='TestCampaign',Start_Date__c=System.today(), End_Date__c=System.today()+2, 
                                   Age_Range__c='46-55', Status__c='In progress', VotingLocation__c=newLocation.Id); 

        Database.insert(newCampaign);
        Voting__c newVoting = new Voting__c(Name='TestVoting', Voting_Campaign__c=newCampaign.Id);
        Database.insert(newVoting);
        Voting_Question_Option__c newOption = new Voting_Question_Option__c(Name='VotingOptionTest', Voting__c=newVoting.Id);
        Database.insert(newOption);
    }

    @isTest
    static void testGetVotingsWithoutAnsSuccess(){
        Voting_Campaign__c campaign = [select Id from Voting_Campaign__c where Name = 'TestCampaign' limit 1];
        Voting__c voting = [select Id from Voting__c where Name = 'TestVoting' limit 1];
        User user = [select Id from User where Age_Range__c='46-55' limit 1];
        Voting_Question_Option__c question = [select Id from Voting_Question_Option__c where Name = 'VotingOptionTest' limit 1];
        System.runAs(user) {
            Vote__c newVote = new Vote__c(Voting_Campaign__c=campaign.Id, Voting__c=voting.Id,Voting_Question_Option__c=question.Id);
            List<Voting__c> afterAnswer = ManageVotings.getVotingsWithoutAns(campaign.Id);
            system.assertEquals(0, afterAnswer.size(), 'Incorrectly counted votes');
        }
    }
}