force-app/main/default/objects/Voting_Campaign__c/Voting_Campaign__c.object-meta.xml
<CustomObject>
    <label>Voting Campaign</label>
    <nameField>
        <label>Voting Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Voting Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voting_Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHandlers/VotingCampaign/VotingCampaignsManager.cls
public with sharing class VotingCampaignsManager {
    
    public static void dateValidation(List<Voting_Campaign__c> newRecords) {
        for(Voting_Campaign__c campaign : newRecords)
        {
            if(campaign.Start_Date__c < System.today() || campaign.End_Date__c < campaign.Start_Date__c)
            {
                campaign.addError('Set correct dates!');
            }
        }  
    }
    
    public static void statusChangeValidation(List<Voting_Campaign__c> newRecords) {
        for(Voting_Campaign__c campaigns : newRecords)
        {
            if(campaigns.Status__c == 'Planned')
            {
                campaigns.addError('Camapign Status cannot be changed to Planned!');
            }
        }  
    }

    public static void nameValidation(List<Voting_Campaign__c> newRecords) {
        List<String> campaignsNames = new List<String>();
        for(Voting_Campaign__c camp : [select Name from Voting_Campaign__c])
        {
            campaignsNames.add(camp.Name);
        }
        for(Voting_Campaign__c newCampaigns : newRecords)
        {
            if(campaignsNames.contains(newCampaigns.Name)) 
            {
                newCampaigns.addError('Campaign Name has to be unique!');
            }
        }
    }

}